### ISSUE TITLE
NCCL timeout when fine-tuing use 8*A40 44G

### ISSUE THREAD

**Issue by meareabc** [modelscope/DiffSynth-Studio#489]
encountered NCCL timeout when using this config

····················································································
this is my config:
CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7" python examples/wanvideo/train_wan_t2v.py \
  --task train \
  --train_architecture lora \
  --dataset_path data/example_dataset \
  --output_path ./output \
  --dit_path "models/Wan-AI/Wan2.1-T2V-14B/diffusion_pytorch_model-00001-of-00006.safetensors,models/Wan-AI/Wan2.1-T2V-14B/diffusion_pytorch_model-00002-of-00006.safetensors,models/Wan-AI/Wan2.1-T2V-14B/diffusion_pytorch_model-00003-of-00006.safetensors,models/Wan-AI/Wan2.1-T2V-14B/diffusion_pytorch_model-00004-of-00006.safetensors,models/Wan-AI/Wan2.1-T2V-14B/diffusion_pytorch_model-00005-of-00006.safetensors,models/Wan-AI/Wan2.1-T2V-14B/diffusion_pytorch_model-00006-of-00006.safetensors" \
  --steps_per_epoch 500 \
  --max_epochs 10 \
  --learning_rate 1e-4 \
  --lora_rank 16 \
  --lora_alpha 16 \
  --lora_target_modules "q,k,v,o,ffn.0,ffn.2" \
  --accumulate_grad_batches 1 \
  --training_strategy deepspeed_stage_1 \
  --use_gradient_checkpointing

My program is stuck here:

Using wan_video_dit from ['models/Wan-AI/Wan2.1-T2V-14B/diffusion_pytorch_model-00001-of-00006.safetensors', 'models/Wan-AI/Wan2.1-T2V-14B/diffusion_pytorch_model-00002-of-00006.safetensors', 'models/Wan-AI/Wan2.1-T2V-14B/diffusion_pytorch_model-00003-of-00006.safetensors', 'models/Wan-AI/Wan2.1-T2V-14B/diffusion_pytorch_model-00004-of-00006.safetensors', 'models/Wan-AI/Wan2.1-T2V-14B/diffusion_pytorch_model-00005-of-00006.safetensors', 'models/Wan-AI/Wan2.1-T2V-14B/diffusion_pytorch_model-00006-of-00006.safetensors'].
No wan_video_vae models available.
No wan_video_image_encoder models available.
No wan_video_text_encoder models available.
Using wan_video_dit from ['models/Wan-AI/Wan2.1-T2V-14B/diffusion_pytorch_model-00001-of-00006.safetensors', 'models/Wan-AI/Wan2.1-T2V-14B/diffusion_pytorch_model-00002-of-00006.safetensors', 'models/Wan-AI/Wan2.1-T2V-14B/diffusion_pytorch_model-00003-of-00006.safetensors', 'models/Wan-AI/Wan2.1-T2V-14B/diffusion_pytorch_model-00004-of-00006.safetensors', 'models/Wan-AI/Wan2.1-T2V-14B/diffusion_pytorch_model-00005-of-00006.safetensors', 'models/Wan-AI/Wan2.1-T2V-14B/diffusion_pytorch_model-00006-of-00006.safetensors'].
No wan_video_vae models available.
No wan_video_image_encoder models available.
No wan_video_text_encoder models available.
Using wan_video_dit from ['models/Wan-AI/Wan2.1-T2V-14B/diffusion_pytorch_model-00001-of-00006.safetensors', 'models/Wan-AI/Wan2.1-T2V-14B/diffusion_pytorch_model-00002-of-00006.safetensors', 'models/Wan-AI/Wan2.1-T2V-14B/diffusion_pytorch_model-00003-of-00006.safetensors', 'models/Wan-AI/Wan2.1-T2V-14B/diffusion_pytorch_model-00004-of-00006.safetensors', 'models/Wan-AI/Wan2.1-T2V-14B/diffusion_pytorch_model-00005-of-00006.safetensors', 'models/Wan-AI/Wan2.1-T2V-14B/diffusion_pytorch_model-00006-of-00006.safetensors'].
No wan_video_vae models available.
No wan_video_image_encoder models available.
No wan_video_text_encoder models available.
Using wan_video_dit from ['models/Wan-AI/Wan2.1-T2V-14B/diffusion_pytorch_model-00001-of-00006.safetensors', 'models/Wan-AI/Wan2.1-T2V-14B/diffusion_pytorch_model-00002-of-00006.safetensors', 'models/Wan-AI/Wan2.1-T2V-14B/diffusion_pytorch_model-00003-of-00006.safetensors', 'models/Wan-AI/Wan2.1-T2V-14B/diffusion_pytorch_model-00004-of-00006.safetensors', 'models/Wan-AI/Wan2.1-T2V-14B/diffusion_pytorch_model-00005-of-00006.safetensors', 'models/Wan-AI/Wan2.1-T2V-14B/diffusion_pytorch_model-00006-of-00006.safetensors'].
No wan_video_vae models available.
No wan_video_image_encoder models available.
[2025-03-26 13:56:04,034] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
initializing deepspeed distributed: GLOBAL_RANK: 3, MEMBER: 4/8
[2025-03-26 13:56:21,890] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-03-26 13:56:30,472] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
initializing deepspeed distributed: GLOBAL_RANK: 6, MEMBER: 7/8
initializing deepspeed distributed: GLOBAL_RANK: 1, MEMBER: 2/8
[2025-03-26 13:56:35,318] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-03-26 13:56:35,318] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-03-26 13:56:35,318] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
initializing deepspeed distributed: GLOBAL_RANK: 5, MEMBER: 6/8
initializing deepspeed distributed: GLOBAL_RANK: 7, MEMBER: 8/8
initializing deepspeed distributed: GLOBAL_RANK: 2, MEMBER: 3/8

**Comment by meareabc** [comment]
and my gpus only use a few VRAM:

                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A    106608      G   /usr/lib/xorg/Xorg                              4MiB |
|    0   N/A  N/A    118909      C   ...libexec/gnome-remote-desktop-daemon        264MiB |
|    0   N/A  N/A    119228      G   ...libexec/gnome-remote-desktop-daemon          0MiB |
|    0   N/A  N/A   1160844      G   /usr/lib/xorg/Xorg                              4MiB |
|    0   N/A  N/A   1978236      C   python                                        454MiB |
|    1   N/A  N/A    106608      G   /usr/lib/xorg/Xorg                              4MiB |
|    1   N/A  N/A   1160844      G   /usr/lib/xorg/Xorg                              4MiB |
|    1   N/A  N/A   1979031      C   ...anaconda3/envs/DiffSynth/bin/python        478MiB |
|    2   N/A  N/A    106608      G   /usr/lib/xorg/Xorg                              4MiB |
|    2   N/A  N/A   1160844      G   /usr/lib/xorg/Xorg                              4MiB |
|    2   N/A  N/A   1979032      C   ...anaconda3/envs/DiffSynth/bin/python        478MiB |
|    3   N/A  N/A    106608      G   /usr/lib/xorg/Xorg                              4MiB |
|    3   N/A  N/A   1160844      G   /usr/lib/xorg/Xorg                              4MiB |
|    3   N/A  N/A   1979033      C   ...anaconda3/envs/DiffSynth/bin/python        454MiB |
|    4   N/A  N/A    106608      G   /usr/lib/xorg/Xorg                              4MiB |
|    4   N/A  N/A   1160844      G   /usr/lib/xorg/Xorg                              4MiB |
|    4   N/A  N/A   1979034      C   ...anaconda3/envs/DiffSynth/bin/python        454MiB |
|    5   N/A  N/A    106608      G   /usr/lib/xorg/Xorg                              4MiB |
|    5   N/A  N/A   1160844      G   /usr/lib/xorg/Xorg                              4MiB |
|    5   N/A  N/A   1979035      C   ...anaconda3/envs/DiffSynth/bin/python        478MiB |
|    6   N/A  N/A    106608      G   /usr/lib/xorg/Xorg                              4MiB |
|    6   N/A  N/A   1160844      G   /usr/lib/xorg/Xorg                              4MiB |
|    6   N/A  N/A   1979036      C   ...anaconda3/envs/DiffSynth/bin/python        478MiB |
|    7   N/A  N/A    106608      G   /usr/lib/xorg/Xorg                              4MiB |
|    7   N/A  N/A   1160844      G   /usr/lib/xorg/Xorg                              4MiB |
|    7   N/A  N/A   1979037      C   ...anaconda3/envs/DiffSynth/bin/python        454MiB |
+-----------------------------------------------------------------------------------------+

**Comment by meareabc** [comment]
it works well when using just one gpu

**Comment by qidai2000** [comment]
Hi,

I saw you deleted your comment, so I just leave a message here. Have you solved the problem? I just set CUDA_VISIBLE_DEVICES to "0,1,2,3,4,5,6,7" and it works. 
Also, may I ask how you run the zero_to_fp32.py? I run python zero_to_fp32.py . model.safetensors to generate the .safetensors file and when I load it in inference, I got an error message saying "safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge". Have you encountered this before? Thanks!

**Comment by meareabc** [comment]
> Hi,
> 
> I saw you deleted your comment, so I just leave a message here. Have you solved the problem? I just set CUDA_VISIBLE_DEVICES to "0,1,2,3,4,5,6,7" and it works. Also, may I ask how you run the zero_to_fp32.py? I run python zero_to_fp32.py . model.safetensors to generate the .safetensors file and when I load it in inference, I got an error message saying "safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge". Have you encountered this before? Thanks!

i delete comment because i found "cannot load lora" in log though i combined a safetensor lora
but the code didn't stop and it generated the video seems without lora

**Comment by meareabc** [comment]
> Hi,
> 
> I saw you deleted your comment, so I just leave a message here. Have you solved the problem? I just set CUDA_VISIBLE_DEVICES to "0,1,2,3,4,5,6,7" and it works. Also, may I ask how you run the zero_to_fp32.py? I run python zero_to_fp32.py . model.safetensors to generate the .safetensors file and when I load it in inference, I got an error message saying "safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge". Have you encountered this before? Thanks!

i fixed my problem, it seems gpu_2 and gpu_3 cannot used into nccl.
when i set "export CUDA_VISIBLE_DEVICES=0,1,4,5,6,7", it works

wierd......

**Comment by meareabc** [comment]
solved this problem by update nccl and reboot system
