### ISSUE TITLE
cuda error

### ISSUE THREAD

**Issue by qinjinsoft** [modelscope/DiffSynth-Studio#52]
![image](https://github.com/modelscope/DiffSynth-Studio/assets/23090414/2e168f6f-cdbe-4f5c-a7c9-51de033867eb)
My computer has CUDA correctly installed and it works fine with other open-source projects. However, when I start this project, I get this error and cannot use other features.

**Comment by qinjinsoft** [comment]
Here is the translation of your message into English:

Due to my CUDA version being 12.4, when I installed the project, it automatically installed PyTorch version 2.3.1+cpu for me. I executed the command pip uninstall torch torchvision torchaudio, and then installed the corresponding version from https://pytorch.org/. This solved the problem. I hope this can help others too.

**Comment by SparrowCapt** [comment]
Hello! How should i know corresponding version?
